### ISSUE TITLE
TESTING still tracks live equity

### ISSUE THREAD

**Issue by Geczy** [aseylys/KStock#4] opened 2018-05-02 14:02 UTC
This skews the "today's profit" that the TESTING data plays with 

Live equity should be frozen I think and move up or down with the TESTING stock data

**Comment by aseylys** [comment] 2018-05-02 15:34
Sorry about the bug, I sure you wish you would've waited an hour because I just released a giant update that takes care of 90% of the bugs, actually fulfills the orders, and has a million UI updates. 

This, along with your other error were fixed in this update.

**Closed as completed by aseylys** 2018-05-02 15:34 UTC

**Comment by Geczy** [comment] 2018-05-02 15:35
Wow, awesome! I'll try it out

**Comment by Geczy** [comment] 2018-05-02 15:48
Latest version still tracking live equity

**Comment by aseylys** [comment] 2018-05-02 15:54
Oh, I see what you're saying now. But that's not a bug, that was deliberate. 

Why wouldn't you want a graph of your equity? That's what Robinhood is graphing in the app.

Sure it doesn't mean much when you're testing, but once you're live trading it's very relevant, because you're equity is changing with the profits. Total Profit and the Transaction Table are the main viewing points during testing.

**Comment by Geczy** [comment] 2018-05-02 15:57
Well yeah it's very relevant live trading. I just meant for testing
