### ISSUE TITLE
vector bug

### ISSUE THREAD

**Issue by Geczy** [aseylys/KStock#1] opened 2018-04-04 13:29 UTC
```
root _ INFO _ MSFT Reached ST Buy Criteria At 89.71
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
```

Nice job on the release by the way !

**Comment by Geczy** [comment] 2018-04-04 13:30
More issues soon as the stock market opened:

```
C:\Users\Matt\AppData\Local\Programs\Python\Python36-32\lib\site-packages\h5py\_            _init__.py:36: FutureWarning: Conversion of the second argument of issubdtype fr            om `float` to `np.floating` is deprecated. In future, it will be treated as `np.            float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "KStock.py", line 654, in <module>
    ex = MainWindow()
  File "KStock.py", line 85, in __init__
    self.update()
  File "KStock.py", line 528, in update
    self.graph.plot(list(xdict.keys()), self.graphData[1], pen = self.ePen, clea            r = False)
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python36-32\lib\site-package            s\pyqtgraph\graphicsItems\PlotItem\PlotItem.py", line 636, in plot
    item = PlotDataItem(*args, **kargs)
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python36-32\lib\site-package            s\pyqtgraph\graphicsItems\PlotDataItem.py", line 177, in __init__
    self.setData(*args, **kargs)
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python36-32\lib\site-package            s\pyqtgraph\graphicsItems\PlotDataItem.py", line 461, in setData
    self.updateItems()
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python36-32\lib\site-package            s\pyqtgraph\graphicsItems\PlotDataItem.py", line 487, in updateItems
    self.curve.setData(x=x, y=y, **curveArgs)
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python36-32\lib\site-package            s\pyqtgraph\graphicsItems\PlotCurveItem.py", line 307, in setData
    self.updateData(*args, **kargs)
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python36-32\lib\site-package            s\pyqtgraph\graphicsItems\PlotCurveItem.py", line 353, in updateData
    raise Exception("X and Y arrays must be the same shape--got %s and %s." % (s            elf.xData.shape, self.yData.shape))
Exception: X and Y arrays must be the same shape--got (0,) and (1,).
```

**Comment by aseylys** [comment] 2018-04-04 15:56
The vector bug seems to be caused by concurrent process automatically quitting after trying to handle the transaction. Right now it's completely benign and the transaction will go through. A later update will handle that more appropriately.

The plot Exception seems to be from a slight overlook. That will be fixed the minute I stop typing this. Thank you for that catch.

**Closed as completed by aseylys** 2018-04-04 15:56 UTC
